// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR13X8XpEU0b_2lhcwtSZxCdfaz915iNw',
    appId: '1:260517101149:web:334a2c6dfeb513074857b4',
    messagingSenderId: '260517101149',
    projectId: 'localtaskapp',
    authDomain: 'localtaskapp.firebaseapp.com',
    storageBucket: 'localtaskapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsYcKIrjOHdxyZHOl_dC5pGX56vwu3FE',
    appId: '1:260517101149:android:dc733a492bb4d62e4857b4',
    messagingSenderId: '260517101149',
    projectId: 'localtaskapp',
    storageBucket: 'localtaskapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBWJCA479yPT1gwZRHqVcZtlCX4BbGaA',
    appId: '1:260517101149:ios:e78b69b41cd860e94857b4',
    messagingSenderId: '260517101149',
    projectId: 'localtaskapp',
    storageBucket: 'localtaskapp.appspot.com',
    iosBundleId: 'com.example.localtaskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVBWJCA479yPT1gwZRHqVcZtlCX4BbGaA',
    appId: '1:260517101149:ios:38a6a5b54a1651b24857b4',
    messagingSenderId: '260517101149',
    projectId: 'localtaskapp',
    storageBucket: 'localtaskapp.appspot.com',
    iosBundleId: 'com.example.localtaskapp.RunnerTests',
  );
}
